#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavisca.PaymentStatusService.ResourceLayer.DataModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dTripDataWareHouse_Sync_v_4_4")]
	public partial class PaymentStatusDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PaymentStatusDataContext() : 
				base(global::Tavisca.PaymentStatusService.ResourceLayer.Properties.Settings.Default.dTripDataWareHouse_Sync_v_4_4ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PaymentStatusDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaymentStatusDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaymentStatusDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaymentStatusDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertTripFolderDetails_dboPaymentStatus")]
		public int spInsertTripFolderDetails_dboPaymentStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripFolderId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> tripFolderId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripProductId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> tripProductId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestType", DbType="NVarChar(256)")] string requestType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResponseTime", DbType="Float")] System.Nullable<double> responseTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NVarChar(32)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierRequestTime", DbType="DateTime")] System.Nullable<System.DateTime> supplierRequestTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierResponseTime", DbType="DateTime")] System.Nullable<System.DateTime> supplierResponseTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Money")] System.Nullable<decimal> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierResponse", DbType="NVarChar(MAX)")] string supplierResponse, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApiSessionId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> apiSessionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tripFolderId, tripProductId, requestType, responseTime, status, supplierRequestTime, supplierResponseTime, amount, supplierResponse, apiSessionId);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
